CREATE TABLE proyectos (
id INT UNSIGNED AUTO_INCREMENT,
nombre VARCHAR(30) NOT NULL,
costo_total FLOAT(8,2) DEFAULT 0.0,
utilidad FLOAT(5,2) DEFAULT 0.0,
disponible FLOAT(8,2) DEFAULT 0.0,
PRIMARY KEY (id)
);

CREATE TABLE pagos (
id_pago INT AUTO_INCREMENT,
id_proyecto INT UNSIGNED,
tipo_pago TINYINT(1) NOT NULL,
monto FLOAT(8,2) NOT NULL, 
fecha DATETIME DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY (id_pago),
FOREIGN KEY (id_proyecto) REFERENCES proyectos(id)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE users (
username VARCHAR(20) NOT NULL,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(50),
reg_date DATETIME DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY (username)
);

CREATE TABLE gastos (
id_gasto INT AUTO_INCREMENT,
id_proyecto INT UNSIGNED,
username VARCHAR(20) NOT NULL,
monto FLOAT(8,2) NOT NULL, 
fecha DATETIME DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY (id_gasto)
FOREIGN KEY (id_proyecto) REFERENCES proyectos(id),
FOREIGN KEY (username) REFERENCES users(username)
ON DELETE CASCADE ON UPDATE CASCADE
);